services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: users
      POSTGRES_USER: cv_auth_backend
      POSTGRES_PASSWORD: pass-cv1234
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: